all: server client bot

server: server.cpp common.h
	g++ --std=c++11 -oserver server.cpp

client: client.cpp common.h
	g++ --std=c++11-oclient client.cpp

bot: bot.cpp common.h
	g++ --std=c++11-obot bot.cpp
